baseURL = 'https://patricklau.dev/'
languageCode = 'en-us'
title = 'Patrick Lau | AI & Automation Leadership'
theme = ''

[params]
  description = 'Vice President with 20+ years of experience in Automation, AI, cybersecurity, and enterprise platform delivery'
  author = 'Patrick Lau'
  email = 'ppklau@gmail.com'
  phone = '+44 7378286446'
  linkedin = 'https://www.linkedin.com/in/patricklau001'
  location = 'London, United Kingdom'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'About'
    url = '/#about'
    weight = 2
  [[menu.main]]
    name = 'Experience'
    url = '/#experience'
    weight = 3
  [[menu.main]]
    name = 'Articles'
    url = '/blog/'
    weight = 4
  [[menu.main]]
    name = 'Contact'
    url = '/#contact'
    weight = 5

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML', 'RSS']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
